// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxxmnicpzxusrpvdszck.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4eG1uaWNwenh1c3JwdmRzemNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNjY0NDEsImV4cCI6MjA2Nzk0MjQ0MX0.p1yPpNggB93S8purZdq16EjlMqf-HBY7sAaYXEy7jK4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});